'use strict';

let words = (function () {
  let wordList = {
    list1: [
      'and',
      'band',
      'came',
      'cone',
      'drive',
      'from',
      'hand',
      'hair',
      'into',
      'jump',
      'land',
      'make',
      'need',
      'part',
      'play',
      'slide',
      'spot',
      'tell',
      'than',
      'three',
      'two',
      'when',
      'will',
    ],
    list2: [
      'steer',
      'later',
      'tooth',
      'again',
      'begin',
      'bright',
      'dress',
      'surfing',
      'spring',
      'third',
      'friend',
      'write',
      'boiled',
      'bread',
      'eight',
      'made',
      'fight',
      'sleet',
      'fried',
      'found',
      'many',
      'twelve',
      'chase',
      'across',
      'snail',
      'think',
      'number',
      'child',
      'clothes',
      'they',
      'already',
      'water',
      'daybreak',
      'yellow',
      'spinach',
      'seven',
      'flights',
      'awake',
      'tooth',
      'clown',
      'after',
      'stamp',
      'scared',
      'bright',
    ],
    list3: [
      'spaghetti',
      'baseball',
      'straighten',
      'backpack',
      'acceptable',
      'airplane',
      'acceptable',
      'recover',
      'birthday',
      'another',
      'tropical',
      'counting',
      'camping',
      'watchfully',
      'excitement',
      'delighted',
    ]
  };

  // function putLettersOnGrid() {}

  return {
    wordList,
    // putLettersOnGrid,
  };
})();

export { words };
